/**
 * Token generator — tokens/tokens.json is the single source of truth; this
 * emits both consumers of it:
 *
 *   src/generated/tokens.css — the custom-property blocks (primitives on
 *     :root, semantics per theme, OS preference honoured, data-theme wins)
 *   src/generated/tokens.ts  — the typed mirror for code that cannot read
 *     CSS: canvas rendering, the card export pipeline, inline SVG
 *
 * Before this existed the two were maintained by hand and drifted silently,
 * with exported card PNGs quietly diverging from the app (#97).
 *
 *   node scripts/generate-tokens.mjs           write the outputs
 *   node scripts/generate-tokens.mjs --check   fail if they are stale (CI)
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(root, "tokens", "tokens.json");
const CSS_OUT = join(root, "src", "generated", "tokens.css");
const TS_OUT = join(root, "src", "generated", "tokens.ts");

const BANNER = "GENERATED by scripts/generate-tokens.mjs from tokens/tokens.json — do not edit.";

/** Object entries minus the `$comment` documentation keys. */
const entries = (obj) => Object.entries(obj).filter(([k]) => k !== "$comment");

/** `{color.navy-950}` -> the primitive at primitive.color["navy-950"]. */
function lookup(primitive, path) {
  const [group, ...rest] = path.split(".");
  const value = primitive[group]?.[rest.join(".")];
  if (value === undefined) throw new Error(`Unknown primitive reference {${path}}`);
  return { group, name: rest.join("."), value };
}

/**
 * Colour primitives get a custom property of their own so themes remap by
 * reassigning semantics. Scales have nothing to remap, so their references
 * inline to the literal and the primitive tier stays out of the CSS.
 */
function resolve(primitive, raw, { asVar }) {
  return String(raw).replace(/\{([^}]+)\}/g, (_match, path) => {
    const ref = lookup(primitive, path);
    return asVar && ref.group === "color" ? `var(--${ref.name})` : ref.value;
  });
}

/** Flatten a semantic subtree into [customPropertyName, value] pairs. */
function flatten(node, prefix = []) {
  const out = [];
  for (const [key, value] of entries(node)) {
    if (value !== null && typeof value === "object") out.push(...flatten(value, [...prefix, key]));
    else out.push([[...prefix, key].join("-"), value]);
  }
  return out;
}

function declarations(primitive, node, asVar) {
  return flatten(node)
    .map(([name, value]) => `  --${name}: ${resolve(primitive, value, { asVar })};`)
    .join("\n");
}

function themeBlock(primitive, theme) {
  const parts = [`  color-scheme: ${theme.scheme};`];
  if (theme.color !== undefined) parts.push(declarations(primitive, theme.color, true));
  if (theme.composite !== undefined) parts.push(declarations(primitive, theme.composite, true));
  return parts.join("\n");
}

function buildCss({ primitive, semantic }) {
  const ramps = entries(primitive.color)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");

  return `/* ${BANNER} */

/* Primitive colour ramps. Theme-independent raw values — components must never
   consume these directly; use the semantic roles below. */
:root {
${ramps}
}

/* Theme-invariant semantics: scales, motion, layout constants. */
:root {
${declarations(primitive, semantic.common, true)}
}

/* Dark is the product default and the fallback when no preference is expressed. */
:root {
${themeBlock(primitive, semantic.dark)}
}

/* The OS preference decides unless the user has made an explicit choice. */
@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) {
${themeBlock(primitive, semantic.light)
  .split("\n")
  .map((line) => `  ${line}`)
  .join("\n")}
  }
}

/* An explicit choice always wins, in both directions. */
[data-theme="light"] {
${themeBlock(primitive, semantic.light)}
}

[data-theme="dark"] {
${themeBlock(primitive, semantic.dark)}
}
`;
}

const camel = (name) => name.replace(/-(.)/g, (_m, c) => c.toUpperCase());
const quoted = (name) => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name));

/** "16px" -> 16, "140ms" -> 140, "700" -> 700. For scales that are pure magnitudes. */
function magnitude(value) {
  const match = /^(-?\d+(?:\.\d+)?)(px|ms)?$/.exec(value);
  if (match === null) throw new Error(`Expected a px/ms magnitude, got "${value}"`);
  return Number(match[1]);
}

function tsRecord(name, node, primitive, transform, doc) {
  const body = entries(node)
    .map(
      ([key, value]) =>
        `  ${quoted(camel(key))}: ${transform(resolve(primitive, value, { asVar: false }))},`,
    )
    .join("\n");
  return `${doc}\nexport const ${name} = {\n${body}\n} as const;\n`;
}

function buildTs({ primitive, semantic }) {
  const num = (v) => String(magnitude(v));
  const str = (v) => JSON.stringify(v);
  const common = semantic.common;

  const paletteKeys = entries(semantic.dark.color).map(([key]) => camel(key));
  const paletteFor = (theme) =>
    entries(theme.color)
      .map(
        ([key, value]) =>
          `  ${camel(key)}: ${JSON.stringify(resolve(primitive, value, { asVar: false }))},`,
      )
      .join("\n");

  return `/* ${BANNER} */

/**
 * Typed mirror of the design tokens, for code that cannot read CSS custom
 * properties: canvas rendering, the card export pipeline and inline SVG.
 */

/** Raw colour ramps. Prefer a semantic role from \`palettes\` where one exists. */
export const primitiveColors = {
${entries(primitive.color)
  .map(([name, value]) => `  ${quoted(camel(name))}: ${JSON.stringify(value)},`)
  .join("\n")}
} as const;

${tsRecord("space", common.space, primitive, num, "/** Spacing scale, in px. */")}
${tsRecord("radius", common.radius, primitive, num, "/** Corner radii, in px. Each step has a stated use — see tokens.json. */")}
${tsRecord("duration", common.dur, primitive, num, "/** Motion durations, in ms. */")}
${tsRecord("easing", common.ease, primitive, str, "/** Easing curves, as CSS timing functions. */")}
${tsRecord("breakpoint", common.bp, primitive, num, "/** Width breakpoints, in px. Mobile-first: these are min-widths. */")}
${tsRecord("container", common.container, primitive, num, "/** Max content widths, in px. */")}
${tsRecord("fontFamily", common.font, primitive, str, "/** Font stacks. */")}
${tsRecord("fontSize", common.text, primitive, str, "/** Type scale. The display end is fluid, so these can be clamp() expressions. */")}
${tsRecord("lineHeight", common.leading, primitive, str, "/** Line heights, paired with the type scale. */")}
${tsRecord("fontWeight", common.weight, primitive, num, "/** Font weights. */")}
${tsRecord("tracking", common.tracking, primitive, str, "/** Letter spacing. */")}
/** Minimum interactive target, in px. */
export const touchMin = ${magnitude(resolve(primitive, common["touch-min"], { asVar: false }))};

/** Flat semantic colour roles. Gradients and shadows are CSS-only. */
export interface Palette {
${paletteKeys.map((key) => `  ${key}: string;`).join("\n")}
}

export const darkPalette: Palette = {
${paletteFor(semantic.dark)}
};

export const lightPalette: Palette = {
${paletteFor(semantic.light)}
};

export type ThemeName = "dark" | "light";

export const palettes: Record<ThemeName, Palette> = {
  dark: darkPalette,
  light: lightPalette,
};
`;
}

/**
 * Format exactly as `prettier --write` would, resolving the repo config for
 * the target path. Anything less and `pnpm format:check` disagrees with the
 * generator, which turns two green gates into a loop.
 */
async function format(source, filepath) {
  const config = await prettier.resolveConfig(filepath);
  return prettier.format(source, { ...config, filepath });
}

async function main() {
  const source = JSON.parse(await readFile(SOURCE, "utf8"));
  const outputs = [
    [CSS_OUT, await format(buildCss(source), CSS_OUT)],
    [TS_OUT, await format(buildTs(source), TS_OUT)],
  ];

  if (process.argv.includes("--check")) {
    const stale = [];
    for (const [path, expected] of outputs) {
      const actual = await readFile(path, "utf8").catch(() => null);
      if (actual !== expected) stale.push(path);
    }
    if (stale.length > 0) {
      console.error(
        `Generated tokens are stale:\n${stale.map((p) => `  ${p}`).join("\n")}\n` +
          `Run \`pnpm --filter @deckxi/ui tokens\` and commit the result.`,
      );
      process.exit(1);
    }
    console.log("Generated tokens are up to date.");
    return;
  }

  for (const [path, contents] of outputs) await writeFile(path, contents);
  console.log(`Wrote ${CSS_OUT} and ${TS_OUT}`);
}

await main();
