/**
 * Derived overall rating (0–100): role-weighted mean of normalised stat
 * values. Regenerated by the pipeline whenever stats change — never edited
 * by hand.
 */
import type { Player, PlayerRole, StatDefinition } from "@deckxi/shared";

/** Per-role stat weights; keys absent from a map fall back to weight 1. */
const ROLE_WEIGHTS: Record<PlayerRole, Record<string, number>> = {
  batter: { battingAvg: 3, strikeRate: 3, runs: 2, wickets: 0.25, economy: 0.25, catches: 1 },
  bowler: { battingAvg: 0.25, strikeRate: 0.25, runs: 0.25, wickets: 3, economy: 3, catches: 1 },
  "all-rounder": { battingAvg: 2, strikeRate: 2, runs: 1, wickets: 2, economy: 2, catches: 1 },
  keeper: { battingAvg: 2.5, strikeRate: 2.5, runs: 1.5, wickets: 0.1, economy: 0.1, catches: 3 },
};

/** Normalised strength in [0, 1] respecting direction; missing → 0. */
export function normalizedStat(player: Player, def: StatDefinition): number {
  const value = player.stats[def.key];
  if (value === undefined || def.max === def.min) return 0;
  const n = Math.min(1, Math.max(0, (value - def.min) / (def.max - def.min)));
  return def.direction === "higher" ? n : 1 - n;
}

export function computeRating(player: Player, stats: readonly StatDefinition[]): number {
  const weights = ROLE_WEIGHTS[player.role];
  let sum = 0;
  let weightSum = 0;
  for (const def of stats) {
    const w = weights[def.key] ?? 1;
    sum += normalizedStat(player, def) * w;
    weightSum += w;
  }
  return Math.round((weightSum === 0 ? 0 : (sum / weightSum) * 100) * 10) / 10;
}

/** Returns players with freshly derived ratings. */
export function regenerateRatings(
  players: readonly Player[],
  stats: readonly StatDefinition[],
): Player[] {
  return players.map((p) => ({ ...p, rating: computeRating(p, stats) }));
}
