/**
 * Card data schemas — the contract for versioned editions in `packages/data`.
 *
 * An edition is the complete dataset a game is played on: stat definitions,
 * teams and player cards. Games pin one edition, so a data refresh never
 * corrupts a running game. Everything is Zod-validated in CI.
 */
import { z } from "zod";

const slug = z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, "lowercase-kebab-case id");
const isoDateTime = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/, "UTC ISO 8601 datetime");

export const statDefinitionSchema = z
  .object({
    key: z.string().regex(/^[a-z][a-zA-Z0-9]*$/, "camelCase stat key"),
    /** Display name, e.g. "Batting average". */
    name: z.string().min(1),
    /** Which end wins a comparison — bowling economy is "lower". */
    direction: z.enum(["higher", "lower"]),
    /**
     * How the UI renders the value. `figures` is a bowling analysis packed
     * into one comparable integer — `wickets * 100 + (99 - runs)` — printed
     * as "w/r"; higher is better, and 0 means "never bowled".
     */
    format: z.enum(["integer", "decimal", "figures"]),
    /** Bounds for normalisation (engine auto-play/bots) and UI bars. */
    min: z.number().finite(),
    max: z.number().finite(),
  })
  .refine((s) => s.min < s.max, { message: "min must be < max" });

export const teamSchema = z.object({
  id: slug,
  name: z.string().min(1),
  /** 2–4 letter abbreviation for compact UI. */
  shortName: z.string().regex(/^[A-Z]{2,4}$/),
  /** Frame colour for the card design system. */
  color: z.string().regex(/^#[0-9a-f]{6}$/i),
});

export const playerRoleSchema = z.enum(["batter", "bowler", "all-rounder", "keeper"]);
export const raritySchema = z.enum(["regular", "star", "legend"]);

/**
 * A licensed photograph of the player. `src` is a site-relative path served
 * by the web app; the rest is the attribution the licence asks us to print.
 */
export const photoSchema = z.object({
  src: z.string().regex(/^\/[a-z0-9./_-]+$/i, "site-relative path"),
  author: z.string().min(1),
  license: z.string().min(1),
  licenseUrl: z.string().url().optional(),
  /** Where the original lives (e.g. the Wikimedia Commons file page). */
  source: z.string().url(),
});

export const playerSchema = z.object({
  id: slug,
  name: z.string().min(1),
  role: playerRoleSchema,
  teamId: slug,
  nationality: z.string().min(1),
  rarity: raritySchema,
  /** Shirt number, where known — printed in the card's corner. */
  jerseyNumber: z.number().int().min(0).max(999).optional(),
  /** Derived overall rating 0–100; regenerated by the data pipeline. */
  rating: z.number().min(0).max(100),
  /** Values for every stat key defined by the edition. */
  stats: z.record(z.string(), z.number().finite()),
  photo: photoSchema.optional(),
});

/** A dataset the edition was derived from, with its licence obligations. */
export const editionSourceSchema = z.object({
  name: z.string().min(1),
  url: z.string().url(),
  license: z.string().min(1),
  licenseUrl: z.string().url().optional(),
  /** What was taken from it and how far it runs, e.g. "men's T20Is to 2026-09-01". */
  note: z.string().optional(),
});

export const editionSchema = z
  .object({
    /** `edition-YYYY-qN` for shipped editions; other slugs for fixtures. */
    id: z.string().regex(/^edition-[a-z0-9]+(-[a-z0-9]+)*$/, "edition-<slug>"),
    name: z.string().min(1),
    /** Bumped by every data refresh within the edition. */
    version: z.number().int().min(1),
    generatedAt: isoDateTime,
    stats: z.array(statDefinitionSchema).min(6).max(10),
    teams: z.array(teamSchema).min(2),
    players: z.array(playerSchema).min(8),
    /** Absent on synthetic editions. Real ones list every dataset they draw on. */
    sources: z.array(editionSourceSchema).optional(),
  })
  .superRefine((edition, ctx) => {
    const dupes = (values: string[]) => values.filter((v, i) => values.indexOf(v) !== i);
    for (const [label, values] of [
      ["stat key", edition.stats.map((s) => s.key)],
      ["team id", edition.teams.map((t) => t.id)],
      ["player id", edition.players.map((p) => p.id)],
    ] as const) {
      for (const d of new Set(dupes([...values]))) {
        ctx.addIssue({ code: "custom", message: `duplicate ${label}: ${d}` });
      }
    }

    const teamIds = new Set(edition.teams.map((t) => t.id));
    const statByKey = new Map(edition.stats.map((s) => [s.key, s]));
    edition.players.forEach((player, i) => {
      const path = ["players", i];
      if (!teamIds.has(player.teamId)) {
        ctx.addIssue({ code: "custom", path, message: `unknown teamId ${player.teamId}` });
      }
      for (const def of edition.stats) {
        const value = player.stats[def.key];
        if (value === undefined) {
          ctx.addIssue({ code: "custom", path, message: `${player.id} missing stat ${def.key}` });
        } else if (value < def.min || value > def.max) {
          ctx.addIssue({
            code: "custom",
            path,
            message: `${player.id} ${def.key}=${value} outside [${def.min}, ${def.max}]`,
          });
        }
      }
      for (const key of Object.keys(player.stats)) {
        if (!statByKey.has(key)) {
          ctx.addIssue({ code: "custom", path, message: `${player.id} has unknown stat ${key}` });
        }
      }
    });
  });

export type StatDefinition = z.infer<typeof statDefinitionSchema>;
export type Team = z.infer<typeof teamSchema>;
export type PlayerRole = z.infer<typeof playerRoleSchema>;
export type Rarity = z.infer<typeof raritySchema>;
export type Player = z.infer<typeof playerSchema>;
export type PlayerPhoto = z.infer<typeof photoSchema>;
export type EditionSource = z.infer<typeof editionSourceSchema>;
export type Edition = z.infer<typeof editionSchema>;

/** Pack a bowling analysis into the comparable `figures` integer. */
export function packFigures(wickets: number, runs: number): number {
  return wickets * 100 + (99 - Math.min(99, Math.max(0, runs)));
}

/** Unpack a `figures` value; null for 0, the "never bowled" sentinel. */
export function unpackFigures(value: number): { wickets: number; runs: number } | null {
  const v = Math.round(value);
  if (v <= 0) return null;
  return { wickets: Math.floor(v / 100), runs: 99 - (v % 100) };
}
