/**
 * Card data schemas — the contract for versioned editions in `packages/data`.
 *
 * An edition is the complete dataset a game is played on: stat definitions,
 * teams and player cards. Games pin one edition, so a data refresh never
 * corrupts a running game. Everything is Zod-validated in CI.
 */
import { z } from "zod";

const slug = z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, "lowercase-kebab-case id");
const isoDateTime = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/, "UTC ISO 8601 datetime");

export const statDefinitionSchema = z
  .object({
    key: z.string().regex(/^[a-z][a-zA-Z0-9]*$/, "camelCase stat key"),
    /** Display name, e.g. "Batting average". */
    name: z.string().min(1),
    /** Which end wins a comparison — bowling economy is "lower". */
    direction: z.enum(["higher", "lower"]),
    /** How the UI renders the value. */
    format: z.enum(["integer", "decimal"]),
    /** Bounds for normalisation (engine auto-play/bots) and UI bars. */
    min: z.number().finite(),
    max: z.number().finite(),
  })
  .refine((s) => s.min < s.max, { message: "min must be < max" });

export const teamSchema = z.object({
  id: slug,
  name: z.string().min(1),
  /** 2–4 letter abbreviation for compact UI. */
  shortName: z.string().regex(/^[A-Z]{2,4}$/),
  /** Frame colour for the card design system. */
  color: z.string().regex(/^#[0-9a-f]{6}$/i),
});

export const playerRoleSchema = z.enum(["batter", "bowler", "all-rounder", "keeper"]);
export const raritySchema = z.enum(["regular", "star", "legend"]);

export const playerSchema = z.object({
  id: slug,
  name: z.string().min(1),
  role: playerRoleSchema,
  teamId: slug,
  nationality: z.string().min(1),
  rarity: raritySchema,
  /** Derived overall rating 0–100; regenerated by the data pipeline. */
  rating: z.number().min(0).max(100),
  /** Values for every stat key defined by the edition. */
  stats: z.record(z.string(), z.number().finite()),
});

export const editionSchema = z
  .object({
    id: z.string().regex(/^edition-\d{4}-q[1-4]$/, "edition-YYYY-qN"),
    name: z.string().min(1),
    /** Bumped by every data refresh within the edition. */
    version: z.number().int().min(1),
    generatedAt: isoDateTime,
    stats: z.array(statDefinitionSchema).min(6).max(7),
    teams: z.array(teamSchema).min(2),
    players: z.array(playerSchema).min(8),
  })
  .superRefine((edition, ctx) => {
    const dupes = (values: string[]) => values.filter((v, i) => values.indexOf(v) !== i);
    for (const [label, values] of [
      ["stat key", edition.stats.map((s) => s.key)],
      ["team id", edition.teams.map((t) => t.id)],
      ["player id", edition.players.map((p) => p.id)],
    ] as const) {
      for (const d of new Set(dupes([...values]))) {
        ctx.addIssue({ code: "custom", message: `duplicate ${label}: ${d}` });
      }
    }

    const teamIds = new Set(edition.teams.map((t) => t.id));
    const statByKey = new Map(edition.stats.map((s) => [s.key, s]));
    edition.players.forEach((player, i) => {
      const path = ["players", i];
      if (!teamIds.has(player.teamId)) {
        ctx.addIssue({ code: "custom", path, message: `unknown teamId ${player.teamId}` });
      }
      for (const def of edition.stats) {
        const value = player.stats[def.key];
        if (value === undefined) {
          ctx.addIssue({ code: "custom", path, message: `${player.id} missing stat ${def.key}` });
        } else if (value < def.min || value > def.max) {
          ctx.addIssue({
            code: "custom",
            path,
            message: `${player.id} ${def.key}=${value} outside [${def.min}, ${def.max}]`,
          });
        }
      }
      for (const key of Object.keys(player.stats)) {
        if (!statByKey.has(key)) {
          ctx.addIssue({ code: "custom", path, message: `${player.id} has unknown stat ${key}` });
        }
      }
    });
  });

export type StatDefinition = z.infer<typeof statDefinitionSchema>;
export type Team = z.infer<typeof teamSchema>;
export type PlayerRole = z.infer<typeof playerRoleSchema>;
export type Rarity = z.infer<typeof raritySchema>;
export type Player = z.infer<typeof playerSchema>;
export type Edition = z.infer<typeof editionSchema>;
