/**
 * Card data schemas — the contract for versioned editions in `packages/data`.
 *
 * An edition is the complete dataset a game is played on: stat definitions,
 * teams and player cards. Games pin one edition, so a data refresh never
 * corrupts a running game. Everything is Zod-validated in CI.
 */
import { z } from "zod";

const slug = z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, "lowercase-kebab-case id");
const isoDateTime = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/, "UTC ISO 8601 datetime");

/**
 * A column on the card. A cricket card has two — batting and bowling — and
 * so does every other sport's, because the card design has two; what they
 * are called and which stats sit in them is the edition's business (#143).
 */
export const statGroupSchema = z.object({
  id: slug,
  /** Column heading, e.g. "Batting". */
  name: z.string().min(1),
  /** Glyph key for the column icon; unknown keys draw a neutral one. */
  icon: slug.optional(),
});

export const statDefinitionSchema = z
  .object({
    key: z.string().regex(/^[a-z][a-zA-Z0-9]*$/, "camelCase stat key"),
    /** Display name, e.g. "Batting average". */
    name: z.string().min(1),
    /** The card column this stat prints in; one of the edition's `statGroups`. */
    group: slug.optional(),
    /** The card's cramped label, e.g. "Avg."; falls back to `name`. */
    short: z.string().min(1).max(8).optional(),
    /** One line of "what this measures", for the rules sheet. */
    blurb: z.string().min(1).max(160).optional(),
    /** Which end wins a comparison — bowling economy is "lower". */
    direction: z.enum(["higher", "lower"]),
    /**
     * How the UI renders the value. `integer` and `decimal` are universal;
     * `figures` is cricket-only — a bowling analysis packed into one
     * comparable integer (`wickets * 100 + (99 - runs)`), printed as "w/r",
     * higher better, 0 meaning "never bowled". An edition for another sport
     * simply never uses it.
     */
    format: z.enum(["integer", "decimal", "figures"]),
    /** Bounds for normalisation (engine auto-play/bots) and UI bars. */
    min: z.number().finite(),
    max: z.number().finite(),
  })
  .refine((s) => s.min < s.max, { message: "min must be < max" });

export const teamSchema = z.object({
  id: slug,
  name: z.string().min(1),
  /** 2–4 letter abbreviation for compact UI. */
  shortName: z.string().regex(/^[A-Z]{2,4}$/),
  /** Frame colour for the card design system. */
  color: z.string().regex(/^#[0-9a-f]{6}$/i),
});

/**
 * What a card *does* — a batter, a bowler, a main-eventer. The vocabulary is
 * the edition's, not the codebase's (#143): a hard-coded cricket enum here
 * would make every other sport either a second app or a lie ("keeper" meaning
 * "technician"). An edition declares its own roles and every card carries one
 * of their ids; deck filters and the UI read this list.
 */
export const roleDefinitionSchema = z.object({
  id: slug,
  /** Display name, e.g. "All-rounder". */
  name: z.string().min(1),
  /** Short form for chips and card corners, e.g. "AR". */
  shortName: z.string().min(1).max(12),
});

export const raritySchema = z.enum(["regular", "star", "legend"]);

/**
 * A deck the edition ships with (#143): the cuts of its own cards that are
 * worth playing. "Batters' XI" is a cricket idea and "The Bloodline" is a
 * wrestling one, so both live in their edition's data file rather than in
 * this package. Operators add more at runtime through the deck catalogue.
 */
export const editionDeckSchema = z.object({
  id: slug,
  name: z.string().min(1).max(40),
  blurb: z.string().min(1).max(160),
  /** Cards must match every filter present; absent filters match everything. */
  roles: z.array(slug).min(1).optional(),
  rarities: z.array(raritySchema).min(1).optional(),
  /** Explicit membership, in this order; wins over the filters when present. */
  cardIds: z.array(slug).min(1).optional(),
  /** Order in the picker; lower first, ties fall back to the name. */
  sort: z.number().int().min(0).max(999).optional(),
});

/**
 * A licensed photograph of the player. `src` is a site-relative path served
 * by the web app; the rest is the attribution the licence asks us to print.
 */
export const photoSchema = z.object({
  src: z.string().regex(/^\/[a-z0-9./_-]+$/i, "site-relative path"),
  author: z.string().min(1),
  license: z.string().min(1),
  licenseUrl: z.string().url().optional(),
  /** Where the original lives (e.g. the Wikimedia Commons file page). */
  source: z.string().url(),
});

export const playerSchema = z.object({
  id: slug,
  name: z.string().min(1),
  /** One of the edition's `roles`; validated against them, not an enum. */
  role: slug,
  teamId: slug,
  nationality: z.string().min(1),
  rarity: raritySchema,
  /** Shirt number, where known — printed in the card's corner. */
  jerseyNumber: z.number().int().min(0).max(999).optional(),
  /** Derived overall rating 0–100; regenerated by the data pipeline. */
  rating: z.number().min(0).max(100),
  /** Values for every stat key defined by the edition. */
  stats: z.record(z.string(), z.number().finite()),
  photo: photoSchema.optional(),
});

/**
 * A power card in the edition's own words (#143). The *rules* are the mode's
 * and never move — a re-skin is copy, not mechanics, which is what keeps a
 * second sport from growing a second engine. Keyed by the power's id, so
 * `powerplay` prints as "Run-In" on a wrestling card and still takes one
 * extra card off everyone it beat.
 */
export const powerSkinSchema = z.object({
  name: z.string().min(1),
  /** Two or three letters for the chip. */
  short: z.string().min(1).max(4),
  /** The line under the name, e.g. "double down". */
  tag: z.string().min(1),
  blurb: z.string().min(1),
  when: z.string().min(1),
  win: z.string().min(1),
  fail: z.string().min(1),
});

/** A dataset the edition was derived from, with its licence obligations. */
export const editionSourceSchema = z.object({
  name: z.string().min(1),
  url: z.string().url(),
  license: z.string().min(1),
  licenseUrl: z.string().url().optional(),
  /** What was taken from it and how far it runs, e.g. "men's T20Is to 2026-09-01". */
  note: z.string().optional(),
});

export const editionSchema = z
  .object({
    /** `edition-YYYY-qN` for shipped editions; other slugs for fixtures. */
    id: z.string().regex(/^edition-[a-z0-9]+(-[a-z0-9]+)*$/, "edition-<slug>"),
    name: z.string().min(1),
    /** Bumped by every data refresh within the edition. */
    version: z.number().int().min(1),
    generatedAt: isoDateTime,
    /**
     * The sport this edition is of, e.g. `cricket`. Lets the UI pick its
     * vocabulary and art direction without guessing from the id.
     */
    sport: slug,
    /** The competition or era the cards are drawn from, where it narrows the sport. */
    series: z.string().min(1).optional(),
    /**
     * The game modes this edition can be played in — the lobby offers the
     * intersection of this and the mode registry. Squad Draft knows about
     * bowlers, keepers and overs, so an edition that has none of those says
     * so here rather than shipping a mode that cannot mean anything.
     */
    supportedModes: z.array(slug).min(1),
    stats: z.array(statDefinitionSchema).min(6).max(10),
    /** The card's two columns. Absent splits the stats evenly and unlabelled. */
    statGroups: z.array(statGroupSchema).max(2).optional(),
    roles: z.array(roleDefinitionSchema).min(1),
    /** The decks this edition ships with. Absent means one deck: all of it. */
    decks: z.array(editionDeckSchema).min(1).optional(),
    /** Power cards renamed for this edition; absent leaves the defaults. */
    powers: z.record(slug, powerSkinSchema).optional(),
    teams: z.array(teamSchema).min(2),
    players: z.array(playerSchema).min(8),
    /** Absent on synthetic editions. Real ones list every dataset they draw on. */
    sources: z.array(editionSourceSchema).optional(),
  })
  .superRefine((edition, ctx) => {
    const dupes = (values: string[]) => values.filter((v, i) => values.indexOf(v) !== i);
    for (const [label, values] of [
      ["stat key", edition.stats.map((s) => s.key)],
      ["role id", edition.roles.map((r) => r.id)],
      ["stat group id", (edition.statGroups ?? []).map((g) => g.id)],
      ["deck id", (edition.decks ?? []).map((d) => d.id)],
      ["team id", edition.teams.map((t) => t.id)],
      ["player id", edition.players.map((p) => p.id)],
    ] as const) {
      for (const d of new Set(dupes([...values]))) {
        ctx.addIssue({ code: "custom", message: `duplicate ${label}: ${d}` });
      }
    }

    const groupIds = new Set((edition.statGroups ?? []).map((g) => g.id));
    edition.stats.forEach((stat, i) => {
      if (stat.group !== undefined && !groupIds.has(stat.group)) {
        ctx.addIssue({
          code: "custom",
          path: ["stats", i],
          message: `${stat.key} is in unknown stat group ${stat.group}`,
        });
      }
    });

    const teamIds = new Set(edition.teams.map((t) => t.id));
    const roleIds = new Set(edition.roles.map((r) => r.id));
    const cardIds = new Set(edition.players.map((p) => p.id));
    (edition.decks ?? []).forEach((deck, i) => {
      const path = ["decks", i];
      for (const role of deck.roles ?? []) {
        if (!roleIds.has(role)) {
          ctx.addIssue({
            code: "custom",
            path,
            message: `${deck.id} filters unknown role ${role}`,
          });
        }
      }
      for (const id of deck.cardIds ?? []) {
        if (!cardIds.has(id)) {
          ctx.addIssue({ code: "custom", path, message: `${deck.id} lists unknown card ${id}` });
        }
      }
    });
    const statByKey = new Map(edition.stats.map((s) => [s.key, s]));
    edition.players.forEach((player, i) => {
      const path = ["players", i];
      if (!teamIds.has(player.teamId)) {
        ctx.addIssue({ code: "custom", path, message: `unknown teamId ${player.teamId}` });
      }
      if (!roleIds.has(player.role)) {
        ctx.addIssue({ code: "custom", path, message: `unknown role ${player.role}` });
      }
      for (const def of edition.stats) {
        const value = player.stats[def.key];
        if (value === undefined) {
          ctx.addIssue({ code: "custom", path, message: `${player.id} missing stat ${def.key}` });
        } else if (value < def.min || value > def.max) {
          ctx.addIssue({
            code: "custom",
            path,
            message: `${player.id} ${def.key}=${value} outside [${def.min}, ${def.max}]`,
          });
        }
      }
      for (const key of Object.keys(player.stats)) {
        if (!statByKey.has(key)) {
          ctx.addIssue({ code: "custom", path, message: `${player.id} has unknown stat ${key}` });
        }
      }
    });
  });

export type StatDefinition = z.infer<typeof statDefinitionSchema>;
export type StatGroup = z.infer<typeof statGroupSchema>;
export type Team = z.infer<typeof teamSchema>;
export type RoleDefinition = z.infer<typeof roleDefinitionSchema>;
export type EditionDeck = z.infer<typeof editionDeckSchema>;
export type PowerSkin = z.infer<typeof powerSkinSchema>;
/** A role id: whatever the edition called it. */
export type PlayerRoleId = string;
export type Rarity = z.infer<typeof raritySchema>;
export type Player = z.infer<typeof playerSchema>;
export type PlayerPhoto = z.infer<typeof photoSchema>;
export type EditionSource = z.infer<typeof editionSourceSchema>;
export type Edition = z.infer<typeof editionSchema>;

/** The edition's name for a role id, falling back to the id itself. */
export function roleName(
  edition: Pick<Edition, "roles"> | null | undefined,
  roleId: string,
): string {
  return edition?.roles.find((r) => r.id === roleId)?.name ?? roleId;
}

/** Pack a bowling analysis into the comparable `figures` integer. */
export function packFigures(wickets: number, runs: number): number {
  return wickets * 100 + (99 - Math.min(99, Math.max(0, runs)));
}

/** Unpack a `figures` value; null for 0, the "never bowled" sentinel. */
export function unpackFigures(value: number): { wickets: number; runs: number } | null {
  const v = Math.round(value);
  if (v <= 0) return null;
  return { wickets: Math.floor(v / 100), runs: 99 - (v % 100) };
}
